name: 'Setup Slack'
description: 'Add slack-message command'
inputs:
  channel:
    description: 'Default slack channel to use'
  token:
    description: 'Slack bot auth token'
  webhook:
    description: 'Slack web hook url'
runs:
  using: "composite"
  steps:
    - run:  |
        chmod a+x "${{ github.action_path }}/bin/slack-message"
        echo "${{ github.action_path }}/bin" >> $GITHUB_PATH
        echo SLACK_ACCESS_TOKEN=${{ inputs.token }} >> $GITHUB_ENV
        echo SLACK_WEBHOOK=${{ inputs.webhook }} >> $GITHUB_ENV
        echo SLACK_CHANNEL=${{ inputs.channel }} >> $GITHUB_ENV
      shell: bash